version: '3'

services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: rtb_house_home_task_app
    networks:
      - postgres-network
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5432/rtb_house_task
      - RANDOM_DATA_API_URL=https://random-data-api.com/api/v2
    depends_on:
      database:
        condition: service_healthy

  database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rtb_house_task
    networks:
      - postgres-network
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks: 
  postgres-network:
    driver: bridge